version: "3.8"

services:
  backend:
    image: favina-backend
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
        - JWT_SECRET=${JWT_SECRET}
        - JWT_EXPIRATION=${JWT_EXPIRATION:-1d}
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=production
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION:-1d}
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - PORT=${PORT:-5001}
      - TYPEORM_LOGGING=${TYPEORM_LOGGING:-true}
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_data:
